### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by jans23** [gsauthof/frank#2]
I use Ubuntu 18.04 and installed inema with `pip install inema`. When executing `frank --list-formats` it fails with

```
Traceback (most recent call last):
  File "/home/user/.local/bin/frank", line 7, in <module>
    from inema.frank import main
  File "/home/user/.local/lib/python2.7/site-packages/inema/frank.py", line 143
SyntaxError: Non-ASCII character '\xc3' in file /home/user/.local/lib/python2.7/site-packages/inema/frank.py on line 144, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Any idea how to fix it?

**Comment by szszszsz** [comment]
I see frank is a Python 3 tool, while you have installed it via Python's 2 pip apparently.
Could you try installing it through `pip3`?

Edit: readme confirms `pip3` has to be used for installation. Perhaps some guard against running tool with Python2 should be added?

Edit: Please remove the Python2 package first.
```
pip uninstall inema
pip3 install inema --user
```

**Comment by szszszsz** [comment]
It unfortunately does not work for me anyway on Python3.6 with:
```
$ pip3 install --user inema
(...)
sz@feather:~$ frank --list-formats
Traceback (most recent call last):
  File "/home/sz/.local/bin/frank", line 10, in <module>
    sys.exit(main())
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 470, in main
    return imain(args)
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 450, in imain
    parse_addresses(args, conf)
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 323, in parse_addresses
    sender.append(parse_address(r, conf))
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 261, in parse_address
    h = conf['a.'+s[1:]]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'a.default'

```

<details>

<summary> same with 'frank --list-formats x297' </summary>

```
1 sz@feather:~$ frank --list-formats x297
Traceback (most recent call last):
  File "/home/sz/.local/bin/frank", line 10, in <module>
    sys.exit(main())
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 470, in main
    return imain(args)
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 450, in imain
    parse_addresses(args, conf)
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 323, in parse_addresses
    sender.append(parse_address(r, conf))
  File "/home/sz/.local/lib/python3.6/site-packages/inema/frank.py", line 261, in parse_address
    h = conf['a.'+s[1:]]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'a.default'

```

 </details>

Edit: trying with Python 3.8.

**Comment by szszszsz** [comment]
Actually that error probably comes from the lack of the config file.

Edit: confimed `frank` works with the config taken from the Readme file.

```
(frank) 1 sz@feather:~/work/frank$ cat > ~/.config/frank.conf
[api]
id = your-partner-id
key = your-api-key
key_phase = 1

[account]
user = portokasse-user
password = portokasse-pw

[a.default]
first =
name = Firma ACME
street = Lindenallee
number = 3
zip = 12345
city = Bielefeld

(frank) sz@feather:~/work/frank$ frank
2020-01-06 19:07:43 - ERROR    - Soap request is not valid. Unknown channel: your-partner-id ! (None) [inema.frank]

```

**Comment by jans23** [comment]
Using `pip3` instead of `pip` solves the issue. It would be nice to have inema detect and avoid such situations.

**Comment by gsauthof** [comment]
Yes, Python 3 is strongly recommended for this package - and in general.

The thing is this: there are still some Python 2 users of the inema library who plan to keep using Python 2 for some time. On the other hand the frank command that is part of the inema package is probably primarily used with Python 3. And I only use Python 2 if strictly necessary.

Thus, unfortunately, I can't just require Python >= 3 for this package.

I can fix the original encoding issue (root cause: in contrast Python 3, Python 2 isn't UTF-8 by default, thus one has to add a pragma to each .py file that contains UTF-8).

Perhaps I'll also add a warning at the top of the README which ideally also shows up on the package's PyPi page.

On the bright side, Python 2 is officially end-of-support since 2020-01-01. Thus, most distributions drop Python 2 sooner than later. For example, Fedora 31 already has dropped it and `pip` is actually Python 3 pip on Fedora 31.
